include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
### [Değiştirdiklerim - False] ###
# /// şeklindeki dokümantasyon yorumlarını zorunlu tutma.
    public_member_api_docs: false
# Proje içi importlarda paket bazlı import kullanımını zorunlu tutma
    always_use_package_imports: false